# Generated by Django 5.0.1 on 2024-03-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('correct', models.CharField(max_length=256)),
                ('wrong_1', models.CharField(max_length=256)),
                ('wrong_2', models.CharField(max_length=256)),
                ('wrong_3', models.CharField(max_length=256)),
            ],
        ),
    ]
