# Generated by Django 5.0.1 on 2024-03-12 13:26

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inventory',
            field=models.JSONField(default=application.models.default_json),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
