# Generated by Django 3.2.24 on 2024-02-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20240225_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='game_user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.profile'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
