# Generated by Django 5.0.1 on 2024-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_profile_inventory_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inventory',
            field=models.JSONField(default={'birds': [], 'bows': [], 'hats': [], 'shoes': []}),
        ),
    ]
