# Generated by Django 5.0.1 on 2024-02-27 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_quiz_score"),
        ("application", "0004_auto_20240225_2244"),
    ]

    operations = []
