# Generated by Django 5.0.1 on 2024-03-12 13:31

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_profile_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inventory',
            field=models.JSONField(default=application.models.default_json),
        ),
    ]
