# Generated by Django 5.0.1 on 2024-03-12 14:13

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_profile_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='accessories',
            field=models.JSONField(default=application.models.default_json_bird),
        ),
    ]
