# Generated by Django 5.0.2 on 2024-03-17 19:42

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_bird_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.JSONField(default=application.models.default_json_shop)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shop',
            },
        ),
    ]
