# Generated by Django 5.0.2 on 2024-03-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='mood',
        ),
    ]
